name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

env:
  wasmpackVersion: 0.8.1
  nodeVersion: 12.18.0

jobs:
  test:
    name: Test Libraries
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - name: Checkout Library Sources
        uses: actions/checkout@v2

      # Install Tooling
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2019-11-04
          override: true
      - name: Install wasm-pack
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-pack --version ${{ env.wasmpackVersion }}
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.nodeVersion }}

      # Caches
      - name: Cache Cargo Registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**Cargo.toml') }}
          restore-keys: ${{ runner.os }}-cargo-registry
      - name: Cache Cargo Test
        uses: actions/cache@v2
        with:
          path: ./target/rust
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**Cargo.toml') }}
          restore-keys: ${{ runner.os }}-cargo-build

      # Lint
      - name: Lint Code
        shell: bash
        run: |
          cargo clippy

      # Tests
      - name: Test Native
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Test WASM
        shell: bash
        run: |
          cd src
          for dir in `ls`; do
              cd $dir;
              wasm-pack test --node;
              cd ..;
          done;
          cd ..
